### ISSUE TITLE
spamming the next media button causes crash or deadlock

### ISSUE THREAD

**Issue by benwaffle** [VaccineApp/vaccine#45]
with webms

**Comment by benwaffle** [comment]
Here's a deadlock stack trace

``` gdb
#0  0x00007ffff48cfcfc in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007ffff48c9bb2 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x00007ffff50ad812 in gst_pad_activate_mode () from /usr/lib/libgstreamer-1.0.so.0
#3  0x00007ffff50ae21a in gst_pad_set_active () from /usr/lib/libgstreamer-1.0.so.0
#4  0x00007ffff509102d in ?? () from /usr/lib/libgstreamer-1.0.so.0
#5  0x00007ffff50a079c in gst_iterator_fold () from /usr/lib/libgstreamer-1.0.so.0
#6  0x00007ffff50913ea in ?? () from /usr/lib/libgstreamer-1.0.so.0
#7  0x00007ffff50930ce in ?? () from /usr/lib/libgstreamer-1.0.so.0
#8  0x00007ffff50932cf in ?? () from /usr/lib/libgstreamer-1.0.so.0
#9  0x00007fffd33adeb8 in ?? () from /usr/lib/gstreamer-1.0/libgstmatroska.so
#10 0x00007ffff5094e52 in gst_element_change_state () from /usr/lib/libgstreamer-1.0.so.0
#11 0x00007ffff5095447 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#12 0x00007ffff5074b83 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#13 0x00007fffd2bb6637 in ?? () from /usr/lib/gstreamer-1.0/libgstplayback.so
#14 0x00007ffff5094e52 in gst_element_change_state () from /usr/lib/libgstreamer-1.0.so.0
#15 0x00007ffff5095447 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#16 0x00007ffff5074b83 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#17 0x00007fffd2bc0ea5 in ?? () from /usr/lib/gstreamer-1.0/libgstplayback.so
#18 0x00007ffff5094e52 in gst_element_change_state () from /usr/lib/libgstreamer-1.0.so.0
#19 0x00007ffff5095447 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#20 0x00007ffff5074b83 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#21 0x00007fffd2bcc2af in ?? () from /usr/lib/gstreamer-1.0/libgstplayback.so
#22 0x00007ffff5094e52 in gst_element_change_state () from /usr/lib/libgstreamer-1.0.so.0
#23 0x00007ffff5095447 in ?? () from /usr/lib/libgstreamer-1.0.so.0
#24 0x0000000000417365 in vaccine_video_preview_real_stop_with_widget (base=0x2fc3750) at src/media/VideoPreview.c:584
#25 0x000000000041165e in vaccine_media_preview_stop_with_widget (self=0x2fc3750) at src/media/MediaPreview.c:311
#26 0x00000000004347e1 in vaccine_media_view_show_media (self=0x2274700, next_media=0x3135380, initial=0) at src/view/MediaView.c:468
#27 0x0000000000435105 in vaccine_media_view_show_next_media (self=0x2274700) at src/view/MediaView.c:588
#28 0x0000000000435123 in _vaccine_media_view_show_next_media_gtk_button_clicked (_sender=0x2de06e0, self=0x2274700) at src/view/MediaView.c:594
#29 0x00007ffff5e48244 in ?? () from /usr/lib/libgobject-2.0.so.0
#30 0x00007ffff5e62a46 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#31 0x00007ffff5e6312f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#32 0x00007ffff75d25cd in ?? () from /usr/lib/libgtk-3.so.0
#33 0x00007ffff75d2635 in ?? () from /usr/lib/libgtk-3.so.0
#34 0x00007ffff5e48015 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#35 0x00007ffff5e59b9c in ?? () from /usr/lib/libgobject-2.0.so.0
#36 0x00007ffff5e62dfc in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#37 0x00007ffff5e6312f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#38 0x00007ffff75d06c0 in ?? () from /usr/lib/libgtk-3.so.0
#39 0x00007fffef8b21f0 in ffi_call_unix64 () from /usr/lib/libffi.so.6
#40 0x00007fffef8b1c58 in ffi_call () from /usr/lib/libffi.so.6
#41 0x00007ffff5e48d65 in g_cclosure_marshal_generic_va () from /usr/lib/libgobject-2.0.so.0
#42 0x00007ffff5e48244 in ?? () from /usr/lib/libgobject-2.0.so.0
#43 0x00007ffff5e62a46 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#44 0x00007ffff5e6312f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#45 0x00007ffff767e861 in ?? () from /usr/lib/libgtk-3.so.0
#46 0x00007ffff5e4ae2e in g_cclosure_marshal_VOID__BOXEDv () from /usr/lib/libgobject-2.0.so.0
#47 0x00007ffff5e48244 in ?? () from /usr/lib/libgobject-2.0.so.0
#48 0x00007ffff5e62a46 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#49 0x00007ffff5e6312f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#50 0x00007ffff767bbbe in ?? () from /usr/lib/libgtk-3.so.0
#51 0x00007ffff767d1e3 in ?? () from /usr/lib/libgtk-3.so.0
#52 0x00007ffff767fdb5 in ?? () from /usr/lib/libgtk-3.so.0
#53 0x00007ffff764fafb in gtk_event_controller_handle_event () from /usr/lib/libgtk-3.so.0
#54 0x00007ffff78001bb in ?? () from /usr/lib/libgtk-3.so.0
#55 0x00007ffff76c4e1a in ?? () from /usr/lib/libgtk-3.so.0
#56 0x00007ffff5e48244 in ?? () from /usr/lib/libgobject-2.0.so.0
#57 0x00007ffff5e62558 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#58 0x00007ffff5e6312f in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#59 0x00007ffff78021fc in ?? () from /usr/lib/libgtk-3.so.0
#60 0x00007ffff76c218e in ?? () from /usr/lib/libgtk-3.so.0
#61 0x00007ffff76c3f3c in gtk_main_do_event () from /usr/lib/libgtk-3.so.0
#62 0x00007ffff723de32 in ?? () from /usr/lib/libgdk-3.so.0
#63 0x00007ffff5b73dc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#64 0x00007ffff5b74020 in ?? () from /usr/lib/libglib-2.0.so.0
#65 0x00007ffff5b740cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#66 0x00007ffff61338ec in g_application_run () from /usr/lib/libgio-2.0.so.0
#67 0x000000000040a22a in _vala_main (args=0x7fffffffe4f8, args_length1=1) at src/App.c:439
#68 0x000000000040a27e in main (argc=1, argv=0x7fffffffe4f8) at src/App.c:455
```
